# Generated by Django 4.2.4 on 2023-08-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
